# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5daeb1d775c1872645b76cf0bf49133375021b34705758bc07ea69496b2370c4f9ff92c69452d9e79ad1b43a7d74b435a00a600248ce3259810fb2cb6934689a

test:
  secret_key_base: b2170402a0f422909e1ca22d8845fe0239a44e3d5348948cf8a52644ac3c139cbe608a454ea9d1d88c1ee4f6cfb85fc3dbd4dc1da966c64d21e2d5ad878fad74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
